### ISSUE TITLE
com.google.android.gms.internal.zzbfm not found

### ISSUE THREAD

**Issue by ftunholm** [mauron85/cordova-plugin-background-geolocation#416]
## Your Environment

* Plugin version: 2.3.5
* Platform:  Android
* OS version: Oreo
* Device manufacturer and model: Samsung S8
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin configuration options: 

    let config: BackgroundGeolocationConfig = {
      desiredAccuracy: 0,
      stationaryRadius: 10,
      distanceFilter: 20,
      interval: 30000,
      debug: true,
      stopOnTerminate: false,
      startOnBoot: true,
      startForeground: false,
      pauseLocationUpdates: false,
      url: '...',
      syncUrl: '...',
      syncThreshold: 5,
      maxLocations: 20,
      httpHeaders: {...},
      stopOnStillActivity: false
    };

    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="^2.3.5">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
        ...
    </plugin>

## Context
I have not been developing for a few days, today I went to run a debug build, some google updates were downloaded before the build step and now it will not build due to error.

## Expected Behavior
I expect the app to build and run

## Actual Behavior
Build fails due to error

## Possible Fix
I don't know, guess it has something to do with some dependency, but i don't know the which or where.

## Debug logs

platforms\android\app\src\main\java\com\marianhello\bgloc\ActivityRecognitionLocationProvider.java:68: error: cannot access zzbfm
        if (lastActivity.getType() == DetectedActivity.STILL) {
                        ^
  class file for com.google.android.gms.internal.zzbfm not found

**Comment by ftunholm** [comment]
That did not do it for me unfortunately, also tried removing platform and adding it. This Ionic stuff is too much, when you just want to sit down and get some coding done for a deadline and this stuff starts xD Well, I don't know what to do, back to research. I'll keep you updated if I find a solution. Thanks

**Comment by grassick** [comment]
We had to form the fcm plugin here to get it to work: https://github.com/mWater/cordova-plugin-fcm

Use this instead: `https://github.com/mWater/cordova-plugin-fcm.git` as the Firebase plugin

**Comment by Chal131313** [comment]
Just run the plugin install with  --variable GOOGLE_PLAY_SERVICES_VERSION=+ . Especially when you have a firebase plugin. The firebase plugins works with version 15.0.0 (latest version -com.google.gms:google-services:+). Its not liking that the location is 11.+ and all others are at the latest (15).

**Comment by ftunholm** [comment]
@Chal131313 I have been running with latest version for a while now. Things seems to work on the outside, maybe I'm just paranoid but it seems my location updates does not occur like they should anymore, it might also be something else i've done.

**Comment by Poyoman39** [comment]
I fixed the issue using this plugin : https://github.com/dpa99c/cordova-android-play-services-gradle-release
with following installing it with following command : 
`cordova plugin add cordova-android-play-services-gradle-release --variable PLAY_SERVICES_VERSION=16.+`
